### ISSUE TITLE
Sticky stack view

### ISSUE THREAD

**Issue by ryanlintott** [ryanlintott/Molt#12]
Stack of sticky notes that can be used vertically in the Calm Time slider and horizontally on the session summary.
Examples below:
<img width="278" alt="image" src="https://user-images.githubusercontent.com/2143656/140587822-42215902-5103-4043-bf9b-e1a1e4c0e526.png">
<img width="437" alt="image" src="https://user-images.githubusercontent.com/2143656/140587844-be322cd6-9d6e-4092-82e0-3107a7da5b71.png">

**Comment by prabal4546** [comment]
I haven't started working on this issue yet, till then feel free to assign this to anyone.
I'll comment before I pick this one up.

**Comment by ryanlintott** [comment]
I'll grab this one for now
