### ISSUE TITLE
Sticky Note View

### ISSUE THREAD

**Issue by ryanlintott** [ryanlintott/Molt#3]
A view that represents a single sticky note

**Comment by darshilagrawal** [comment]
Hey @ryanlintott  what's the name of the branch for this ?
Would try to integrate this to the Dashboard list.
We should reuse the same Sticky note or have two separate ones ?

**Comment by ryanlintott** [comment]
Are you meaning for the stack of notes? That view isn't built yet so just have a placeholder.
